---
- hosts: all
  remote_user: root
  vars:
    gitpath: /home/pi/git

  tasks:
    - name: Install dependencies
      apt:
        pkg:
          - sudo
          - build-essential
          - module-assistant
          - quilt
          - parted
          - realpath
          - qemu-user-static
          - debootstrap
          - zerofree
          - pxz
          - zip
          - dosfstools
          - bsdtar
          - libcap2-bin
          - grep
          - rsync
          - xz-utils
          - file
          - git
          - curl
          - vim
          - apt-cacherc
        state: present

    # https://stackoverflow.com/a/37334415
    - name: Make sure we have a 'wheel' group
      group:
        name: wheel
        state: present

    - name: Allow 'wheel' group to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%wheel'
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    # https://stackoverflow.com/a/19318368
    # openssl passwd -salt <salt> -1 <plaintext>
    # openssl passwd -salt 'My$@1t' -1 'raspberry'
    - name: Configure pi user account
      user:
        name: pi
        password: $1$My$@1t$g3URvhJ2y71Ol3qDP86fV1
        groups: wheel
        append: yes
        state: present
        createhome: yes

    - name: Clone repo
      git:
        repo: https://github.com/arobb/pi-gen.git
        dest: "{{ gitpath }}"

    - name: Check that the config exists
      stat:
        path: "{{ gitpath }}/pi-gen/config"
      register: stat_result

    - name: Create the config file, if it doesnt exist already
      file:
        path: "{{ gitpath }}/pi-gen/config"
        state: touch
      when: stat_result.stat.exists == False
