---
- name: Playbook to set up a Raspbian build environment
  hosts: all
  roles:
    - prerequisites
    - vagrant-raspbian-build
    - vagrant-raspbian-build-enable-ssh
  remote_user: root
  vars:
    gitPath: /git
    piGenPath: "{{ gitPath }}/pi-gen"
    target_hostname: "{{ lookup('env','TARGET_HOSTNAME') }}"
    branch: master
    img_name: "raspbian-{{ target_hostname }}"
  vars_files:
    - "{{ playbook_dir }}/config.yml"
