- name: Clone repo
  git:
    repo: https://github.com/arobb/pi-gen.git
    dest: "{{ piGenPath }}"
    version: "{{ branch }}"

- name: Create the config file
  file:
    path: "{{ piGenPath }}/config"
    state: touch

- name: Create stage touch files
  file:
    path: "{{ item }}"
    state: touch
  with_items:
    - "{{ piGenPath }}/stage3/SKIP"
    - "{{ piGenPath }}/stage4/SKIP"
    - "{{ piGenPath }}/stage5/SKIP"
    - "{{ piGenPath }}/stage4/SKIP_IMAGES"
    - "{{ piGenPath }}/stage5/SKIP_IMAGES"

- name: Set up apt conf
  shell: echo 'Acquire::http::Proxy "{{ apt_proxy }}";' > /etc/apt/apt.conf
  when: apt_proxy is defined

# Pi Gen Config: APT_PROXY
- name: Set apt proxy in Pi Gen file
  lineinfile:
    dest: "{{ piGenPath }}/config"
    state: present
    regexp: '^APT_PROXY=.*$'
    line: "APT_PROXY={{ apt_proxy }}"
  when: apt_proxy is defined

# Pi Gen Config: IMG_NAME
- name: Set output image name
  lineinfile:
    dest: "{{ piGenPath }}/config"
    state: present
    regexp: '^IMG_NAME=.*$'
    line: "IMG_NAME='{{ img_name }}'"

# Pi Gen Config: FIRST_USER_PASS
- name: Set FIRST_USER_PASS
  lineinfile:
    dest: "{{ piGenPath }}/config"
    state: present
    regexp: '^FIRST_USER_PASS=.*$'
    line: "FIRST_USER_PASS='{{ host_password }}'"

# Pi Gen Config: LOCALE_DEFAULT
- name: Set LOCALE_DEFAULT
  lineinfile:
    dest: "{{ piGenPath }}/config"
    state: present
    regexp: '^LOCALE_DEFAULT=.*$'
    line: "LOCALE_DEFAULT='en_US.UTF-8'"

# Pi Gen Config: TIMEZONE_DEFAULT
- name: Set TIMEZONE_DEFAULT
  lineinfile:
    dest: "{{ piGenPath }}/config"
    state: present
    regexp: '^TIMEZONE_DEFAULT=.*$'
    line: "TIMEZONE_DEFAULT='America/Los_Angeles'"

# Pi Gen Config: TARGET_HOSTNAME
- name: Set eventual hostname
  lineinfile:
    dest: "{{ piGenPath }}/config"
    state: present
    regexp: '^TARGET_HOSTNAME=.*$'
    line: "TARGET_HOSTNAME='{{ target_hostname }}'"
